### ISSUE TITLE
Add slide number to the `PresentationWidget`

### ISSUE THREAD

**Issue by immadisairaj** [immadisairaj/prides#13]
# Problem
Currently, from the visuals, we won't know what slide we are currently in.

# Proposal
We can add a number of what slide we are currently in by having an optional parameter in the `PresentationWidget`

# Additional Details
There is already a `_currentSlide.value` that keeps track of what slide we are in. We can use the `_currentSlide.value + 1` to show with an optional parameter inside `PresentationWidget` showing it at the top most of the `Stack` at bottom center.

**Comment by morpheus-30** [comment]
Can you assign this issue to me?

**Comment by immadisairaj** [comment]
Great, Thank you @morpheus-30. I've assigned you the issue. You can feel free to ask if you are stuck somewhere.

**Comment by immadisairaj** [comment]
Closing this issue as it is fixed in #14
